#
# Copyright (C) 2019 Signal Messenger, LLC.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-only
#

[package]
name = "ringrtc"
version = "2.5.1"
authors = ["Curt Brune <curt@signal.org>", "Jim Gustafson <jim@signal.org>", "Peter Thatcher <peter@signal.org>", "Vladimir Skuratovich <vlad@signal.org>"]
edition = "2018"
description = "A Rust interface for WebRTC"
license = "GPL-3.0-only"

[lib]
crate_type = ["cdylib", "staticlib", "lib"]

[[bin]]
name = "cli"
path = "src/cli.rs"
required-features = ["native", "simnet"]

[dependencies]
bytes       = { version = "0.5"  }
failure     = { version = "0.1"  }
futures     = { version = "0.1"  }
lazy_static = { version = "1.4"  }
libc        = { version = "0.2"  }
log         = { version = "0.4", features = ["std", "max_level_trace", "release_max_level_info"] }
prost       = { version = "0.6"  }
rand        = { version = "0.7", features = [] }
regex       = { version = "1.3"  }

# Optional, needed to build protobufs
prost-build = { version = "0.6.1", optional = true }

# Optional, needed by the 'sim' feature
simplelog   = { version = "0.7", optional = true, default-features = false }
rand_chacha = { version = "0.2", optional = true }

# Optional, needed by the "electron" feature
neon = { version = "0.4.0", optional = true }

[build-dependencies]
# Needed by the "electron" feature
neon-build = "0.4.0"

[dependencies.tokio]
version = "=0.1.22"
default-features = false
features = ["rt-full"]

[features]
default = []
protobuf_gen_deps = ["prost-build"]
sim = ["simplelog", "rand_chacha"]
electron = ["neon", "native"]
native = []  # We have this so we can more easily disable things only native clients need
simnet = []  # We have this so we can more easily disable things only simulated native client need

[[bin]]
name = "protobuf-gen"
path = "protobuf/protobuf_gen.rs"
required-features = ["protobuf_gen_deps"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.13.0", default-features = false }

[patch.crates-io]
mio = { git = "https://github.com/signalapp/mio.git", branch = "v0.6.19br" }
